services:
  web:
    image: zeropoll-web
    build:
      dockerfile: ./docker/web/Dockerfile
      context: ../..
      args:
        - NEXT_PUBLIC_PROTOKIT_GRAPHQL_URL=${NEXT_PUBLIC_PROTOKIT_GRAPHQL_URL}
    container_name: zeropoll-web
    environment:
      - NEXT_PUBLIC_PROTOKIT_GRAPHQL_URL=${NEXT_PUBLIC_PROTOKIT_GRAPHQL_URL}
    profiles:
      - web
    depends_on:
      - sequencer
    networks:
      - routing-net
      - chain-net
    ports:
      - 3000:3000
