name: Test Chain Module

on:
  push:
    branches:
      - main
      - develop
      - "feature/*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm@9.8.0

      - name: Install dependencies
        run: pnpm install

      - name: Run tests for chain module
        run: pnpm run test --filter @zeropoll/chain
